artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion/samsum
  repo_id: knkarthick/samsum
  local_dir_use_symlinks: false

data_validation:
  root_dir: artifacts/data_ingestion/samsum
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.csv", "test.csv", "validation.csv", "README.md"]
  ALL_REQUIRED_COLUMNS: ["dialogue", "summary"]



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum
  tokenizer_path: sshleifer/distilbart-cnn-12-6



model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: sshleifer/distilbart-cnn-12-6



model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  metric_file_name: artifacts/model_evaluation/metrics.csv
  base_model_path: sshleifer/distilbart-cnn-12-6